dexscreener:
  base-url: /tokens/v1/{chainId}/{tokenAddresses}
  tokens:
    solana:
      - symbol: RFC_USDT
        address: C3DwDjT17gDvvCYC2nsdGHxDHVmQRdhKfpAdqQ29pump
      - symbol: ALCH_USDT
        address: HNg5PYJmtqcmzXrv6S9zP1CDKk5BgDuyFBxbvNApump

pancake:
  router-address: "0x10ED43C718714eb63d5aA57B78B54704E256024E"
  wrapped-bnb:   "0xBB4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
  busd:          "0xe9e7cea3dedca5984780bafc599bd69add087d56"
  tokens:
#    RFC: "0xHNg5PYJmtqcmzXrv6S9zP1CDKk5BgDuyFBxbvNAp"
    Cake: "0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82"
#    RFC: 0x...
  update-interval: 5000
bsc:
  rpc-url: https://bsc-dataseed.binance.org/


management:
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields:
        - request_id
      correlation:
        fields:
          - request_id
    propagation:
      type: b3
    metrics:
      enable:
        jvm: true
        system: true
        process: true
      distribution:
        percentiles-histogram:
          "[api.calls.latency]": true
        percentiles:
          "[api.calls.latency]": 0.5, 0.95, 0.99
    endpoints:
      web:
        exposure:
          include: health,info,prometheus,metrics,beans

clickhouse:
  url: "jdbc:clickhouse://localhost:8123/arbitrage"
  user: default
  password: default

zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"